### ISSUE TITLE
Some ReadGroups are missing referenceSetId

### ISSUE THREAD

**Issue by jrobinso** [googlegenomics/api-client-python#10]
Some ReadGroup objects are missing the required referenceSetId field.  For example, id=ChdDUFhwN2VLNERSQ0o2b2Fzb2E3enRnaxAA from the Simons Foundation.

**Comment by pgrosu** [comment]
Hi Jim,

So you can always [patch](https://cloud.google.com/genomics/v1beta2/reference/readgroupsets/patch) a `ReadGroupSet` with a `ReferenceSetId`.  Since `ReadGroup`(s) are part of a `ReadGroupSet`, below are the steps using the custom command via the Java client to patch the `ReadGroupSet`:

1) First find what `ReferenceSetID` you want to associate to - in this case I used `hg19`, which is stored as:
```
$ java -jar genomics-tools-client-java-v1beta2.jar searchreferencesets --fields 'referenceSets(id,assemblyId)'
{"assemblyId":"GRCh37lite","id":"EJjur6DxjIa6KQ"}
{"assemblyId":"GRCh38","id":"EMud_c37lKPXTQ"}
{"assemblyId":"hs37d5","id":"EOSt9JOVhp3jkwE"}
{"assemblyId":"GRCh37","id":"EOSsjdnTicvzwAE"}
{"assemblyId":"hg19","id":"EMWV_ZfLxrDY-wE"}
```
2) Noticing hg19's id is `EMWV_ZfLxrDY-wE` and using the [Google APIs Discovery Service for Google Genomics](https://www.googleapis.com/discovery/v1/apis/genomics/v1beta2/rest), I notice that both the `ReadGroupSetID` and `ReferenceSetID` are strings:
```
  "patch": {
     "id": "genomics.readgroupsets.patch",
     "path": "readgroupsets/{readGroupSetId}",
     "httpMethod": "PATCH",
     "description": "Updates a read group set. This method supports patch semantics.",
     "parameters": {
      "readGroupSetId": {
       "type": "string",
       "description": "The ID of the read group set to be updated. The caller must have WRITE permissions to the dataset associated with this read group set.",
       "required": true,
       "location": "path"
      }
...
   "referenceSetId": {
     "type": "string",
     "description": "The ID of the reference set that defines the coordinate space for this set's annotations."
    },
```   
3) Then you can use the custom command to associate in this case `hg19` with your `ReadGroupSetID`:
```
java -jar genomics-tools-client-java-v1beta2.jar custom --custom_endpoint "readgroupsets/YOUR_READGROUPSET_ID" --custom_method PATCH --custom_body '{"referenceSetId":"EMWV_ZfLxrDY-wE"}'
```

Let me know how it goes.

Hope it helps,
Paul

**Comment by jrobinso** [comment]
Hi Paul,  thanks that's helpful but really I was just reporting some out-of-spec data in your public datasets, Nicole asked me to report data problems here as I find them.  Its not a blocking issue for me.

Jim

**Comment by pgrosu** [comment]
Ah, thanks Jim for the clarification :)  

Sorry for the noise,
~p

**Comment by deflaux** [comment]
I did a quick check and it appears that for the datasets listed [here](https://github.com/googlegenomics/api-client-python/blob/master/main.py#L59) both DREAM and Simon's Foundation still need an update.

A few of the others were fixed recently (PGP and Platinum Genomes).

**Comment by deflaux** [comment]
DREAM and Simon's Foundation have both been associated with a referenceSetId now.  Thanks for reporting the issue!
